### PR TITLE
add scala 2.13 and remove 2.10

### PR DESCRIPTION
**Pull request by danbills**

### CODE REVIEW

**Comment by danbills** [comment]
looks like travis is choking on installing the jdk:
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-09-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```
I'll remove the 2.10 travis builds too, since this PR removes 2.10 elsewhere

**Comment by andresilva** [comment]
Thanks for the PR! I'm not actively working with Scala and I don't have a local environment setup right now, it might take me a bit longer to publish this once it's merged. We might want to change the default version to 2.13 instead, and then crosscompile against 2.12 and 2.11.

**Comment by andresilva** [comment]
Also if you could update the versions in the README I'd appreciate it :)

**Comment by pjfanning** [comment]
with travis, openjdk seems to be better supported than oraclejdk - could you try changing .travis.yml to use openjdk8?

**Comment by andresilva** [comment]
Going to merge this and fix travis afterwards. Thanks for the PR :+1:

**Comment by andresilva** [comment]
Released v0.4.3 with Scala 2.13 support.

**Pull request merged**
